name: Call nightly testing workflows

on:
  workflow_dispatch:

jobs:
  spec_testing:
    name: "Spec testing"
    uses: ./.github/workflows/spec.yml

  nightly_testing:
    if: github.repository != 'puppetlabs/puppetlabs-bash_task_helper' && github.repository != 'puppetlabs/puppetlabs-puppet_operations_appliance'
    name: "PE Nightly Testing"
    needs: spec_testing
    uses: ./.github/workflows/pe_nightly_testing.yml
    secrets: inherit
